export default {
    spaceIcon:"     ",
    noPassword: "Sem senha.",
    weekPassword: "Senha fraca",
    confirmSub:"Iremos enviar todas suas informações.",
    usernameRegistred:"Usuário já cadastrado.",
    emailRegistred:"Email já cadastrado.",
    descriptionBenefit:"Adicione um benefício que a vaga possui.",
    descriptionRequirement:"Adicione um requisito para a vaga.",
    strongPassword: "Senha forte.",
    createdVacancy:"Vaga criada com sucesso!",
    failEmail: "Email não cadastrado.",
    userFail:"Usuário não encontrado.",
    failLogin: "Usuário ou senha inválido.",
    regularPassword: "Senha intermediária",
    veryWeekPassword: "Senha muito fraca.",
    confirmLogout:"Deseja encerrar sessão?",
    updated:"Dados atualizados com sucesso!",
    benefitDeleted:"Benefício deletado com sucesso!",
    requirementDeleted:"Requisito deletado com sucesso!",
    confirmDeleteUser:"Deseja excluir sua conta?",
    failUpdate:"Não foi possível atualizar os dados.",
    verificationCode: 'Código inválido ou expirado.',
    requested:"Aluno(a) solicitado.",
    indicated:"Aluno(a) indicado.",
    failVacancies:"Não foi possível consultar as vagas.",
    failStudents:"Não foi possível consultar os alunos.",
    differentPasswords: "As senhas devem ser iguais.",
    coursesFail: "Não foi possível consultar os cursos.",
    locationError:"Não foi possível pegar a localização.",
    misssingEmail: 'Por favor inserir novamente o email.',
    failTeachers:"Não foi possível consultar os professores.",
    failCompanies:"Não foi possível consultar as empresas.",
    descriptionExperience:"Adicione uma experiência profissional.",
    currentLocationError:"Não foi possível pegar a localização atual",
    dateEndFail:"Data de conclusão deve ser menor que a data de Início",
    descriptionLanguage:"Adicione o nome do idioma é o nível de compreensão.",
    descriptionProject:"Adicione um projeto relacionado a sua área fora da faculdade.",
    descriptionFormation:"Adicione uma formação de algum curso da área.",
    descriptionNetwork: "Adicione uma rede social que mostre seu progresso profissional e acadêmico como Linkedin ou github.",
    descriptionTeacher: "Professores ou coordenadores tem permissão para indicar alunos para as vagas. Se você é um coordenador de estágio contate o administrador para poder gerenciar vagas.",
    descriptionStudent: "Alunos podem se inscrever nas vagas , ser indicado e solicitados para vagas de estágio ou emprego.",
    descriptionCompany: "Empresas tem permissão para postar e gerenciar vagas de emprego ou estágio, solicitar candidatos e recebem indicações dos professores.",
}