export default {
    spaceIcon:"     ",
    noPassword: "Sem senha.",
    weekPassword: "Senha fraca",
    strongPassword: "Senha forte.",
    failEmail: "Email não cadastrado.",
    failLogin: "Usuário ou senha inválido.",
    regularPassword: "Senha intermediária",
    veryWeekPassword: "Senha muito fraca.",
    verificationCode: 'Código inválido ou expirado.',
    differentPasswords: "As senhas devem ser iguais.",
    coursesFail: "Não foi possível consultar os cursos.",
    misssingEmail: 'Por favor inserir novamente o email.',
    descriptionExperience:"Adicione uma experiência profissional.",
    descriptionLanguage:"Adicione o nome do idioma é o nível de compreensão.",
    descriptionProject:"Adicione um projeto relacionado a sua área fora da faculdade.",
    descriptionFormation:"Adicione uma formação de algum curso da área.",
    descriptionNetwork: "Adicione uma rede social que mostre seu progresso profissional e acadêmico como Linkedin ou github.",
    descriptionTeacher: "Professores ou coordenadores tem permissão para indicar alunos para as vagas. Se você é um coordenador de estágio contate o administrador para poder gerenciar vagas.",
    descriptionStudent: "Alunos podem se inscrever nas vagas , ser indicado e solicitados para vagas de estágio ou emprego.",
    descriptionCompany: "Empresas tem permissão para postar e gerenciar vagas de emprego ou estágio, solicitar candidatos e recebem indicações dos professores.",
}