from routes.job import *
from routes.auth import *
from routes.news import *
from routes.users import *
from routes.course import *
from routes.benefit import *
from routes.project import *
from routes.language import *
from routes.formation import *
from routes.experience import *
from routes.subscription import *
from routes.requirement import *
from routes.socialNetwork import *