from routes.job import *
from routes.auth import *
from routes.users import *
from routes.benefit import *
from routes.project import *
from routes.language import *
from routes.formation import *
from routes.experience import *
from routes.requirement import *
from routes.socialNetwork import *